trigger:
  - main

pr:
- '*'

variables:
- group: AzureKeyVault
- name: BUILD_COUNTER
  value: $[counter('buildnumber', 0)]

pool:
  vmImage: windows-latest
steps:
- task: UseDotNet@2
  displayName: Install .NET Core 3.1 SDK
  inputs:
    version: '3.1.x'
    packageType: sdk
- task: UseDotNet@2
  displayName: Install .NET Core 2.1 SDK
  inputs:
    version: '2.1.x'
    packageType: sdk
- powershell: ./build.ps1 -ci
  displayName: Invoke build.ps1
  env:
    KEYVAULT_CLIENT_SECRET: $(kv-access-token)
- publish: artifacts/
  artifact: Packages
  displayName: Publish artifacts
